// AUTH action types
export const AUTH_ACTION_REQUEST = 'AUTH_ACTION_REQUEST';
export const AUTH_ACTION_SUCCESS = 'AUTH_ACTION_SUCCESS';
export const AUTH_ACTION_FAILURE = 'AUTH_ACTION_FAILURE';
export const AUTH_RESET_REQUEST_STATE = 'AUTH_RESET_REQUEST_STATE';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_GET_PROFILE = 'AUTH_GET_PROFILE';
export const AUTH_UPDATE_MY_PROFILE = 'AUTH_UPDATE_MY_PROFILE';
export const SET_SHIPPING_DETAILS = 'SET_SHIPPING_DETAILS';

// USER action types
export const USER_ACTION_REQUEST = 'USER_ACTION_REQUEST';
export const USER_ACTION_SUCCESS = 'USER_ACTION_SUCCESS';
export const USER_ACTION_FAILURE = 'USER_ACTION_FAILURE';
export const GET_USERS = 'GET_USERS';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';


// PRODUCT action types
export const PRODUCT_ACTION_REQUEST = 'PRODUCT_ACTION_REQUEST';
export const PRODUCT_ACTION_SUCCESS = 'PRODUCT_ACTION_SUCCESS';
export const PRODUCT_ACTION_FAILURE = 'PRODUCT_ACTION_FAILURE';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_LATEST_PRODUCTS = 'GET_LATEST_PRODUCTS';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const PRODUCT_RESET_REQUEST_STATE = 'PRODUCT_RESET_REQUEST_STATE';

// ORDER action types
export const ORDER_ACTION_REQUEST = "ORDER_ACTION_REQUEST"
export const ORDER_ACTION_SUCCESS = "ORDER_ACTION_SUCCESS"
export const ORDER_ACTION_FAILURE = "ORDER_ACTION_FAILURE"
export const GET_ALL_ORDERS = "GET_ALL_ORDERS"
export const GET_SINGLE_ORDER = "GET_SINGLE_ORDER"
export const GET_USER_ORDERS = "GET_USER_ORDERS"
export const CHANGE_ORDER_STATUS = "CHANGE_ORDER_STATUS"

// CART action types
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const CLEAR_CART = "CLEAR_CART"
