// USER action types
export const AUTH_ACTION_REQUEST = 'AUTH_ACTION_REQUEST';
export const AUTH_ACTION_SUCCESS = 'AUTH_ACTION_SUCCESS';
export const AUTH_ACTION_FAILURE = 'AUTH_ACTION_FAILURE';
export const AUTH_RESET_REQUEST_STATE = 'AUTH_RESET_REQUEST_STATE';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_GET_PROFILE = 'AUTH_GET_PROFILE';
export const AUTH_UPDATE_MY_PROFILE = 'AUTH_UPDATE_MY_PROFILE';


// PRODUCT action types
export const PRODUCT_ACTION_REQUEST = 'PRODUCT_ACTION_REQUEST';
export const PRODUCT_ACTION_SUCCESS = 'PRODUCT_ACTION_SUCCESS';
export const PRODUCT_ACTION_FAILURE = 'PRODUCT_ACTION_FAILURE';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
export const GET_LATEST_PRODUCTS = 'GET_LATEST_PRODUCTS';